name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip python3-setuptools python3-wheel fontforge
          sudo pip3 install afdko

      - name: Download and convert fonts
        run: |
          FILENAMES=$(wget http://mirrors.ibiblio.org/CTAN/fonts/garamondx/type1/ -O - | grep -oP 'href="\K[^"]*\.pfb' | sed 's|\.pfb||')
          for FILENAME in $FILENAMES; do
            wget -c "http://mirrors.ibiblio.org/CTAN/fonts/garamondx/type1/${FILENAME}.pfb"
            wget -c "http://mirrors.ibiblio.org/CTAN/fonts/garamondx/afm/${FILENAME}.afm"

            # Determine the style based on the filename
            case "$FILENAME" in
              *Bol*) SUBFAMILY="Bold" ;;
              *Ita*) SUBFAMILY="Italic" ;;
              *SC*) SUBFAMILY="SmallCaps" ;;
              *sups*) SUBFAMILY="Superscript" ;;
              *Osf*) SUBFAMILY="OldStyleFigures" ;;
              *) SUBFAMILY="Regular" ;;
            esac

            # Create a makeotf configuration file
            cat <<EOF > makeotf_config.txt
FamilyName: NewG8
SubfamilyName: $SUBFAMILY
FullName: NewG8 $SUBFAMILY
PostScriptName: NewG8-$FILENAME
EOF

            # Convert .pfb to .otf using makeotf with the configuration file
            makeotf -r -f "${FILENAME}.pfb" -o "${FILENAME}.otf" -m makeotf_config.txt

            # Convert OTF to TTF
            otf2ttf "${FILENAME}.otf"
          done

      - name: Zip the output files
        run: |
          zip -r newg8-otf.zip . -i *.otf
          zip -r newg8-ttf.zip . -i *.ttf

      - name: Upload ZIP files
        uses: actions/upload-artifact@v2
        with:
          name: font-zips
          path: |
            newg8-otf.zip
            newg8-ttf.zip
